EXPLAIN PLAN FOR
SELECT 
    EXNF.DATACADASTRO, 
    COUNT(DISTINCT EXNF.IDNF) AS TOTAL_NOTAS
FROM EXAME_NF EXNF
JOIN EXAME_ITEMNF EXITEM ON EXNF.IDNF = EXITEM.IDNF
WHERE EXITEM.VALOR < 50
GROUP BY EXNF.DATACADASTRO
ORDER BY EXNF.DATACADASTRO;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX IDX_ITEMNF_VALOR ON EXAME_ITEMNF (VALOR);

CREATE INDEX IDX_ITEMNF_IDNF_VALOR ON EXAME_ITEMNF (IDNF, VALOR);

CREATE INDEX IDX_NF_DATACADASTRO ON EXAME_NF (DATACADASTRO);

SELECT 
    EXNF.DATACADASTRO, 
    COUNT(DISTINCT EXNF.IDNF) AS TOTAL_NOTAS
FROM EXAME_NF EXNF
WHERE EXISTS (
    SELECT 1 
    FROM EXAME_ITEMNF EXITEM 
    WHERE EXITEM.IDNF = EXNF.IDNF 
      AND EXITEM.VALOR < 50
)
GROUP BY EXNF.DATACADASTRO
ORDER BY EXNF.DATACADASTRO;


