CREATE TABLE EXAME_NF (
    IDNF NUMBER NOT NULL PRIMARY KEY,
    NUMERO NUMBER NOT NULL,
    DATACADASTRO DATE,
    TOTALGERAL NUMBER
);

CREATE TABLE EXAME_ITEMNF (
    IDITEMNF NUMBER NOT NULL PRIMARY KEY,
    IDNF NUMBER NOT NULL,
    IDPRODUTO NUMBER NOT NULL,
    QTDE NUMBER,
    VALOR NUMBER,
    CONSTRAINT FK_EXAME_ITEMNF_NF FOREIGN KEY (IDNF) REFERENCES EXAME_NF(IDNF)
);

