SELECT 
    EXNF.DATACADASTRO, 
    COUNT(DISTINCT EXNF.IDNF) AS TOTAL_NOTAS
FROM EXAME_NF EXNF
JOIN EXAME_ITEMNF EXITEM ON EXNF.IDNF = EXITEM.IDNF
WHERE EXITEM.VALOR < 50
GROUP BY EXNF.DATACADASTRO
ORDER BY EXNF.DATACADASTRO;