server:
  port: 8081
spring:
  application:
    name: desafio
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true