-- Estrutura de dados Exercício 1 

CREATE TABLE PRODUTO
(IDPRODUTO NUMBER NOT NULL PRIMARY KEY,
CODIGOINTERNO VARCHAR2(60),
DESCR VARCHAR2(120),
ATIVO CHAR(1));

CREATE TABLE EMBALAGEM (
    BARRA VARCHAR2(32) NOT NULL PRIMARY KEY,
    IDPRODUTO NUMBER NOT NULL,
    DESCR VARCHAR2(80),
    FATORCONVERSAO NUMBER,
    ALTURA NUMBER,
    LARGURA NUMBER,
    COMPRIMENTO NUMBER,
    ATIVO CHAR(1),
    CONSTRAINT FK_EMBALAGEM_PRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)  
);

